import 'primeflex/primeflex.css';
import 'primeicons/primeicons.css';
import 'primereact/resources/primereact.min.css';
import 'primereact/resources/themes/bootstrap4-light-blue/theme.css';
import './global.scss';

import ReduxProvider from '@assets/providers/ReduxProvider';
import type { Metadata } from 'next';
import { PropsWithChildren } from 'react';

export const metadata: Metadata = {
	title: 'Hệ thống xử lý tiến trình khóa luận tốt nghiệp 2',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang='en'>
			<ReduxProvider>
				<body className='min-h-screen surface-200'>{children}</body>
			</ReduxProvider>
		</html>
	);
}
