'use client';

import 'primeflex/primeflex.css';
import 'primeicons/primeicons.css';
import 'primereact/resources/primereact.min.css';
import 'primereact/resources/themes/bootstrap4-light-blue/theme.css';
import './global.scss';

import ReduxProvider from '@assets/providers/ReduxProvider';
import { PageProps } from '@assets/types/common';
import { Header, Sidebar } from '@resources/components/layout';
import { dir } from 'i18next';
import type { Metadata } from 'next';
import { useEffect } from 'react';
import { setCookie } from 'cookies-next';

export const metadata: Metadata = {
	title: 'Hệ thống xử lý tiến trình khóa luận tốt nghiệp 2',
	description: 'Generated by create next app',
};

export default function RootLayout({ children, params: { lng } }: PageProps) {
	setCookie('i18next', lng);
	return (
		<html
			lang={lng}
			dir={dir(lng)}
		>
			<head />
			<ReduxProvider>
				<body className='min-h-screen surface-200'>
					<div className='flex'>
						<Sidebar lng={lng} />

						<div className='flex-1'>
							<Header />
							{children}
						</div>
					</div>
				</body>
			</ReduxProvider>
		</html>
	);
}
