'use client';

import 'primeflex/primeflex.css';
import 'primeicons/primeicons.css';
import 'primereact/resources/primereact.min.css';
import 'primereact/resources/themes/bootstrap4-light-blue/theme.css';
import './global.scss';

import ReduxProvider from '@assets/providers/ReduxProvider';
import { PageProps } from '@assets/types/common';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { dir } from 'i18next';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Hệ thống xử lý tiến trình khóa luận tốt nghiệp 2',
	description: 'Generated by create next app',
};

const queryClient = new QueryClient();

export default function RootLayout({ children, params: { lng } }: PageProps) {
	return (
		<html
			lang={lng}
			dir={dir(lng)}
		>
			<ReduxProvider>
				<QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
			</ReduxProvider>
		</html>
	);
}
