import { MenuItemType } from '@assets/types/menu';
import { TFunction } from 'i18next';
import {
    FaBookJournalWhills,
    FaBoxesStacked,
    FaGear,
    FaHouseChimney,
    FaRegNewspaper,
    FaUserGear,
} from 'react-icons/fa6';
import { PERMISSION, ROUTES } from '.';

const ADMIN_MENU = (t: TFunction, lng: string): MenuItemType[] => {
    return [
        {
            code: 'home',
            label: t('menu:home'),
            icon: <FaHouseChimney />,
            parent: 'home',
            to: `/${lng}/${ROUTES.home.index}`,
            permission: '',
            checkPermission: true,
        },
        {
            code: 'admin',
            label: t('menu:admin'),
            parent: 'admin',
            icon: <FaUserGear />,
            to: '',
            permission: '',
            checkPermission: true,
            items: [
                {
                    code: 'faculty',
                    parent: 'admin',
                    label: t('menu:faculty'),
                    to: `/${lng}/${ROUTES.admin.faculty}`,
                    permission: PERMISSION.faculty.view,
                    checkPermission: true,
                },
                {
                    code: 'industry',
                    parent: 'admin',
                    label: t('menu:industry'),
                    to: `/${lng}/${ROUTES.admin.industry}`,
                    permission: PERMISSION.industry.view,
                    checkPermission: true,
                },
                {
                    code: 'major',
                    parent: 'admin',
                    label: t('menu:major'),
                    to: `/${lng}/${ROUTES.admin.major}`,
                    permission: PERMISSION.major.view,
                    checkPermission: true,
                },
                {
                    code: 'department',
                    parent: 'admin',
                    label: t('menu:department'),
                    to: `/${lng}/${ROUTES.admin.department}`,
                    permission: PERMISSION.department.view,
                    checkPermission: true,
                },
            ],
        },
        {
            code: 'master_data',
            label: t('menu:master_data'),
            parent: 'master_data',
            icon: <FaBoxesStacked />,
            to: '',
            permission: '',
            checkPermission: true,
            items: [
                {
                    code: 'teacher',
                    parent: 'master_data',
                    label: t('menu:teacher'),
                    to: `/${lng}/${ROUTES.master_data.teacher}`,
                    permission: PERMISSION.teacher.view,
                    checkPermission: true,
                },
                {
                    code: 'student',
                    parent: 'master_data',
                    label: t('menu:student'),
                    to: `/${lng}/${ROUTES.master_data.student}`,
                    permission: PERMISSION.student.view,
                    checkPermission: true,
                },
                {
                    code: 'registration_period',
                    parent: 'master_data',
                    label: t('menu:registration_period'),
                    to: `/${lng}/${ROUTES.master_data.registration_period}`,
                    permission: PERMISSION.registrationPeriod.view,
                    checkPermission: true,
                },
                {
                    code: 'student_join',
                    parent: 'master_data',
                    label: t('menu:student_join'),
                    to: `/${lng}/${ROUTES.master_data.student_join}`,
                    permission: PERMISSION.studentJoin.view,
                    checkPermission: true,
                },
            ],
        },
        {
            code: 'thesis',
            label: t('menu:thesis'),
            parent: 'thesis',
            icon: <FaBookJournalWhills />,
            permission: '',
            checkPermission: true,
            to: '',
            items: [
                {
                    code: 'topic',
                    parent: 'thesis',
                    label: t('menu:topic'),
                    to: `/${lng}/${ROUTES.thesis.topic}`,
                    permission: PERMISSION.topic.view,
                    checkPermission: true,
                },
                {
                    code: 'group',
                    parent: 'thesis',
                    label: t('menu:group'),
                    to: `/${lng}/${ROUTES.thesis.group}`,
                    permission: PERMISSION.group.view,
                    checkPermission: true,
                },
                {
                    code: 'schedule',
                    parent: 'thesis',
                    label: t('menu:schedule'),
                    to: `/${lng}/${ROUTES.thesis.schedule}`,
                    permission: PERMISSION.studentJoin.view,
                    checkPermission: true,
                },
                {
                    code: 'point',
                    parent: 'thesis',
                    label: t('menu:point'),
                    to: `/${lng}/${ROUTES.thesis.point}`,
                    permission: PERMISSION.studentJoin.view,
                    checkPermission: true,
                },
                {
                    code: 'job',
                    parent: 'thesis',
                    label: t('menu:job'),
                    to: `/${lng}/${ROUTES.thesis.job}`,
                    permission: PERMISSION.job.view,
                    checkPermission: true,
                },
                {
                    code: 'counter',
                    parent: 'thesis',
                    label: t('menu:counter'),
                    to: `/${lng}/${ROUTES.thesis.counter}`,
                    permission: PERMISSION.job.view,
                    checkPermission: true,
                },
            ],
        },
        {
            code: 'information',
            label: t('menu:information'),
            parent: 'information',
            icon: <FaRegNewspaper />,
            permission: '',
            checkPermission: true,
            to: '',
            items: [
                {
                    code: 'notification',
                    label: t('menu:notification'),
                    parent: 'information',
                    permission: PERMISSION.faculty.view,
                    checkPermission: true,
                    to: `/${lng}/${ROUTES.information.notification}`,
                },
                {
                    code: 'faculty_duty',
                    label: t('menu:faculty_duty'),
                    parent: 'information',
                    permission: PERMISSION.faculty.view,
                    checkPermission: true,
                    to: `/${lng}/${ROUTES.information.faculty_duty}`,
                },
                {
                    code: 'department_duty',
                    label: t('menu:department_duty'),
                    parent: 'information',
                    permission: PERMISSION.faculty.view,
                    checkPermission: true,
                    to: `/${lng}/${ROUTES.information.department_duty}`,
                },
            ],
        },
        {
            code: 'system',
            label: t('menu:system'),
            parent: 'system',
            icon: <FaGear />,
            permission: '',
            checkPermission: true,
            to: '',
            items: [
                {
                    code: 'role',
                    label: t('menu:role'),
                    parent: 'system',
                    permission: PERMISSION.role.view,
                    checkPermission: true,
                    to: `/${lng}/${ROUTES.system.role}`,
                },
                {
                    code: 'account',
                    label: t('menu:account'),
                    parent: 'system',
                    permission: PERMISSION.account.view,
                    checkPermission: true,
                    to: `/${lng}/${ROUTES.system.account}`,
                },
            ],
        },
    ];
};

export { ADMIN_MENU };
